apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: devops-test-node-backend
    template: devops-test-node-backend
  name: devops-test-node-backend
  namespace: ci-cd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: devops-test-node-backend
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        name: devops-test-node-backend
      name: devops-test-node-backend
    spec:
      containers:
        - image: >-
            docker-registry.default.svc:5000/ci-cd/devops-test-node-backend
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: devops-test-node-backend
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - devops-test-node-backend
        from:
          kind: ImageStreamTag
          name: 'devops-test-node-backend:latest'
          namespace: ci-cd
      type: ImageChange
    - type: ConfigChange
